name: Riax CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.0' # Define the elixir version [required]
        otp-version: '25.0' # Define the OTP version [required]
    - name: Install dependencies
      run: mix deps.get
    - name: Setup environment and credo
      run: |
        epmd -daemon
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix credo
    - name: Run tests
      run: mix test --trace
